version: '3'

services:
  todotests:
    depends_on:
      - todofront
      - todoback
    environment:
      - FRONT_HOST=todofront
    build: ./todo-app/tests/

  todofront:
    ports:
      - 3000:3000
    depends_on:
      - todoback
    environment:
      - REACT_APP_API_HOST=todoback
    build: ./todo-app/front-end/

  todoback:
    build: ./todo-app/back-end/
    ports:
      - 3001:3001